name: Deploy Next.js 15 to GitHub Pages

on:
  push:
    branches:
      - main   # or master, if that's your default branch

permissions:
  contents: write   # needed to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /escapeelite

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
